#!/usr/bin/env python

import argparse
import cveval

if __name__ == '__main__':

    parser = argparse.ArgumentParser()

    parser.add_argument('name')
    parser.add_argument('selection_file')
    parser.add_argument('sequence_file')
    parser.add_argument('outcome_dir')
    parser.add_argument('output_dir')

    args = parser.parse_args()

    cveval.evaluate(args.name, args.selection_file, args.sequence_file, args.outcome_dir,args.output_dir)

